//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwAsignacionTribunales.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsignacionFechaDefensa
    {
        public int IdAsignacionFechaDefensa { get; set; }
        public Nullable<System.DateTime> FechaDefensa { get; set; }
        public Nullable<System.DateTime> Hora { get; set; }
        public Nullable<int> IdTesis { get; set; }
        public Nullable<decimal> NotaFinalGrado { get; set; }
        public Nullable<bool> Graduado { get; set; }
        public Nullable<bool> IsActivo { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> IdEstudiante { get; set; }
    
        public virtual Tesi Tesi { get; set; }
    }
}
