//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwAsignacionTribunales.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeudasPendientesEstudiante
    {
        public int IdDeudaPendiente { get; set; }
        public string Estudiante { get; set; }
        public System.DateTime FechaVencimiento { get; set; }
        public decimal ValorPendiente { get; set; }
        public string Detalle { get; set; }
        public bool IsPagado { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public string NumeroFactura { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
