//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwAsignacionTribunales.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstudianteHabilitacionEstudiante
    {
        public int IdEstudianteHabilitacionEstudiante { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool IsActivo { get; set; }
        public string IdEstudiante { get; set; }
        public int IdHabilitacionEstudiatne { get; set; }
    
        public virtual HabilitacionEstudiante HabilitacionEstudiante { get; set; }
    }
}
