//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwAsignacionTribunales.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HabilitacionEstudiante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HabilitacionEstudiante()
        {
            this.EstudianteHabilitacionEstudiantes = new HashSet<EstudianteHabilitacionEstudiante>();
            this.ObservacionHabilitacionEstudiantes = new HashSet<ObservacionHabilitacionEstudiante>();
        }
    
        public int IdHabilitacionEstudiante { get; set; }
        public bool IsPasantia { get; set; }
        public bool IsVinculacion { get; set; }
        public bool IsIdioma { get; set; }
        public bool IsFinanciero { get; set; }
        public Nullable<System.DateTime> FechaPasantia { get; set; }
        public Nullable<System.DateTime> FechaVinculacion { get; set; }
        public Nullable<System.DateTime> FechaIdioma { get; set; }
        public Nullable<System.DateTime> FechaFinanciero { get; set; }
        public bool IsHabilitado { get; set; }
        public Nullable<System.DateTime> FechaHabilitado { get; set; }
        public bool IsMallaCurricular { get; set; }
        public Nullable<System.DateTime> FechaMallaCurricular { get; set; }
        public bool IsDocumentoTodos { get; set; }
        public Nullable<System.DateTime> FechaDocumentoTodos { get; set; }
        public Nullable<bool> IsHomologacion { get; set; }
        public Nullable<System.DateTime> FechaHomologacion { get; set; }
        public string DescripcionHomologacion { get; set; }
        public bool IsTema { get; set; }
        public Nullable<System.DateTime> FechaTema { get; set; }
        public int TipoTema { get; set; }
        public int Usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstudianteHabilitacionEstudiante> EstudianteHabilitacionEstudiantes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObservacionHabilitacionEstudiante> ObservacionHabilitacionEstudiantes { get; set; }
    }
}
