//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwAsignacionTribunales.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PracticaVinculacionEstudiante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PracticaVinculacionEstudiante()
        {
            this.SeguimientoPracticasVinculacions = new HashSet<SeguimientoPracticasVinculacion>();
        }
    
        public int IdPracticaVinculacionEstudiante { get; set; }
        public string DocenteTutor { get; set; }
        public string Docente { get; set; }
        public Nullable<bool> MateriaGeneradora { get; set; }
        public Nullable<System.DateTime> FechaPracticaDesde { get; set; }
        public Nullable<decimal> Calificacion { get; set; }
        public Nullable<int> NumeroHora { get; set; }
        public string IdEstudiante { get; set; }
        public Nullable<bool> EstudianteNac { get; set; }
        public string CodigoCertificado { get; set; }
        public Nullable<int> IdMatricula { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> TipoPracticaVinculacion { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
        public Nullable<int> TipoProyecto { get; set; }
        public Nullable<System.DateTime> FechaPracticaHasta { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual PoyectoVinculacion PoyectoVinculacion { get; set; }
        public virtual TipoPracticaVinculacion TipoPracticaVinculacion1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeguimientoPracticasVinculacion> SeguimientoPracticasVinculacions { get; set; }
    }
}
