//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwAsignacionTribunales.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistroAccesoUsuario
    {
        public int IdRegistroAcceso { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Cuenta { get; set; }
        public string Correo { get; set; }
        public System.DateTime FechaAcceso { get; set; }
        public string Tipo { get; set; }
    }
}
