//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwAsignacionTribunales.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tesi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tesi()
        {
            this.AsignacionFechaDefensas = new HashSet<AsignacionFechaDefensa>();
            this.EstudiantePicExamen = new HashSet<EstudiantePicExaman>();
            this.SeguimientoTesis = new HashSet<SeguimientoTesi>();
            this.Tribunals = new HashSet<Tribunal>();
            this.TutoreSeguimientoes = new HashSet<TutoreSeguimiento>();
        }
    
        public int IdTesis { get; set; }
        public string Titulo { get; set; }
        public string IdEstudiante { get; set; }
        public bool IsActivo { get; set; }
        public Nullable<bool> IsTutoria { get; set; }
        public Nullable<System.DateTime> FechaTutoria { get; set; }
        public Nullable<bool> IsRevision { get; set; }
        public Nullable<System.DateTime> FechaRevision { get; set; }
        public Nullable<bool> IsHabilitado { get; set; }
        public Nullable<System.DateTime> FechaHabilitado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignacionFechaDefensa> AsignacionFechaDefensas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstudiantePicExaman> EstudiantePicExamen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeguimientoTesi> SeguimientoTesis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tribunal> Tribunals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TutoreSeguimiento> TutoreSeguimientoes { get; set; }
    }
}
