//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwAsignacionTribunales.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tribunal
    {
        public int IdTribunal { get; set; }
        public string Docente { get; set; }
        public string IdEstudiante { get; set; }
        public Nullable<decimal> Calificacion { get; set; }
        public int IdTipoIntegranteTribunal { get; set; }
        public Nullable<int> IdTesis { get; set; }
    
        public virtual Tesi Tesi { get; set; }
        public virtual TipoIntegranteTribunal TipoIntegranteTribunal { get; set; }
    }
}
