//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwAsignacionTribunales.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutoreSeguimiento
    {
        public int IdTutorSeguimiento { get; set; }
        public int Docente { get; set; }
        public int IdTipoRevision { get; set; }
        public bool IsActivo { get; set; }
        public int IdTesis { get; set; }
    
        public virtual Tesi Tesi { get; set; }
        public virtual TipoRevision TipoRevision { get; set; }
    }
}
