//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwAsignacionTribunales.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Url
    {
        public System.Guid IdGuid { get; set; }
        public int IdUsuario { get; set; }
        public int IdSistema { get; set; }
        public int IdPerfil { get; set; }
        public System.DateTime Fecha { get; set; }
        public bool IsActivo { get; set; }
    }
}
